[profile.default]
solc = '0.8.30'
evm_version='prague'
via_ir = true
optimizer_runs = 4_294_967_295
bytecode_hash = 'none'
src = "src"
out = "out"
libs = ["lib"]
extra_output_files = ["irOptimized"] # NOTE: comment this line to speed up compile times when yul IR output is not required
fuzz.runs = 10_000
dynamic_test_linking = true

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[lint]
exclude_lints = ["mixed-case-function", "mixed-case-variable", "asm-keccak256", "unused-import", "unaliased-plain-import", "screaming-snake-case-const", "screaming-snake-case-immutable", "unsafe-typecast"]
# note that unsafe-typecast is included in this list; remove it to review the respective warnings as part of build