[profile.default]
solc = '0.8.27'
evm_version='cancun'
via_ir = true
optimizer_runs = 4_294_967_295
bytecode_hash = 'none'
src = "src"
out = "out"
libs = ["lib"]
extra_output_files = ["irOptimized"]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
