[profile.default]
solc = '0.8.28'
evm_version='cancun'
via_ir = true
# optimizer_runs = 4_294_967_295
optimizer_runs = 100_000
# optimizer_runs = 200
bytecode_hash = 'none'
src = "src"
out = "out"
libs = ["lib"]
extra_output_files = ["irOptimized"]
fuzz.runs = 10_000

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true