[profile.default]
solc = '0.8.28'
evm_version='cancun'
via_ir = true
# TODO: restore max runs
# optimizer_runs = 4_294_967_295
optimizer_runs = 10_000
bytecode_hash = 'none'
src = "src"
out = "out"
libs = ["lib"]
# NOTE: uncomment to view yul IR output
# extra_output_files = ["irOptimized"]
fuzz.runs = 10_000
dynamic_test_linking = true

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true